name: Deploy Vite Project to GitHub Pages

on:
  push:
    branches: [ main, master ] # 只要你上傳檔案到 main 或 master 就會觸發

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite 打包後的資料夾

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
